### ISSUE TITLE
Verify authenticator attestation

### ISSUE THREAD

**Issue by fgervais** [Yubico/libfido2#12]
I just got my hand on the attestation certificate of a non Yubico authenticatior.

I'd like to perform a signature verification to ensure that I have a genuine device.

I'm looking for the easier way to do this.

Would libfido2 be a good place to start to perform such validation?

**Comment by martelletto** [comment]
this verification is only possible with a copy of the root 
certificate used by the manufacturer for attestation. for yubico 
authenticators, this certificate is currently available at:

https://developers.yubico.com/U2F/yubico-u2f-ca-certs.txt

you could then dump the attestation certificate using libfido2's 
fido_cred_x5c_ptr(3) and fido_cred_x5c_len(3), and use openssl to 
convert and verify it:

$ openssl x509 -inform der -in /tmp/x509.der > /tmp/x509.pem
$ openssl verify -x509_strict -CAfile /tmp/yubico-u2f-ca-certs.txt /tmp/x509.pem
/tmp/x509.pem: OK

doing this in a more robust way in libfido2 is a bit problematic as 
it would involve bundling the certificates used by various vendors 
(leading to issues of trust) and keeping track of them (leading to 
issues of versioning).

that's why libfido2 verifies the generated credential against the 
attestation certificate provided by the device (through 
fido_cred_verify(3)), and allows this certificate to be extracted 
(through fido_cred_x5c_ptr(3)), with verification of the certificate 
itself left at the discretion of the consumer of the library.

-p.

**Comment by fgervais** [comment]
Good that's easy enough, thank you.

Yes I understand managing those certification would be an issue. This is quite an area where FIDO is lacking in my opinion.

The whole public key authentication is really good but the root of the security is based on an untrusted device. In the case of the yubikey, it can be verified on your website so I think it fine. If the device gets replace in the mail let say you wouldn't be incentivised to tell me it's real when it's not. I guess more vendor should implement this device verification on their website.

I'd be interested to see people discussing what a malicious authenticator could do. Since it doesn't require a custom driver nor any custom runtime application maybe it wouldn't be too bad.
