### ISSUE TITLE
Check for vendor extensions and generate clear error messages

### ISSUE THREAD

**Issue by riedel** [Yubico/libfido2#129]
From the readme I get that libfido is vendor indepent.

The spec states: `Command codes in the range between authenticatorVendorFirst and authenticatorVendorLast may be used for vendor-specific implementations. For example, the vendor may choose to put in some testing commands. Note that the FIDO client will never generate these commands. All other command codes are reserved for future use and may not be used.`

Currently the following lines use yubikey specific codes without any precautions (e.g. checking vendor):
https://github.com/Yubico/libfido2/blob/393c18ccc24b71b30340deeebb92f32e4c6b4a42/src/credman.c#L140
https://github.com/Yubico/libfido2/blob/38c0a50f70edb41ecd25be0e4a6fd63fce9fea9b/src/bio.c#L112

Documentation/Specs seems to be missing

The yubikey vendor extentions seem to be suffixed _PRE.

I would suggest a configure switch for dis/enabling those and dependent code.

**Comment by martelletto** [comment]
Hi,

It is up to the application, based on metadata obtained through [fido_dev_get_cbor_info()](https://developers.yubico.com/libfido2/Manuals/fido_dev_get_cbor_info.html), to understand the commands and functionalities supported by an authenticator, and to decide which commands to issue, how, and when. If we move this logic to the library, libfido2 will no longer be vendor independent.

Regarding credential management and the biometric enrollment API, these are features of FIDO 2.1 preview keys. Unfortunately, the unreleased FIDO specs are not publicly available.

-p.

**Comment by riedel** [comment]
So does that mean that  FIDO 2.1  will use the vendor_keys 0x40 and 0x41. That seems rather strange to me. 

Why would a vendor independent library hard code vendor keys of one vendor? My comment was exactly that the mentioned lines or rather https://github.com/Yubico/libfido2/blob/780ad3c258aea5028b7b94c6623a96da3fd55224/src/fido/param.h#L34 breaks vendor independence.

**Comment by martelletto** [comment]
Hi,

> So does that mean that FIDO 2.1 will use the vendor_keys 0x40 and 0x41. That seems rather strange to me.

That means that FIDO 2.1 preview (FIDO_2_1_PRE) uses values 0x40 and 0x41.

> Why would a vendor independent library hard code vendor keys of one vendor? 

You seem to extrapolate from "undocumented" to "one vendor". I completely understand your frustration, but I am afraid that is not the case. FIDO_2_1_PRE is implemented by devices from multiple vendors.

> My comment was exactly that the mentioned lines or rather
> 
> https://github.com/Yubico/libfido2/blob/780ad3c258aea5028b7b94c6623a96da3fd55224/src/fido/param.h#L34
> 
> breaks vendor independence.

Going back to your original point:

If you believe libfido2 support for these features is actively hurting/confusing  authenticators because applications aren't checking for FIDO_2_1_PRE in fido_dev_get_cbor_info(), please consider submitting a PR to said projects.

If you would like to implement firmware support for FIDO_2_1_PRE, or just get a better understanding of what FIDO_2_1_PRE is, please contact the FIDO alliance.

If you just want to chat, feel free to reach out at pedro [at] ambientworks [dot] net. (Disclaimer: I am no longer employed by Yubico and will reply in my own time, like I am doing with this issue.)

Warm regards,

-p.

**Comment by riedel** [comment]
Hi,
thanks for the explaination. (BTW: No frustration, just confusion :). I think the extensions are great! And the closed nature of the FIDO standardization process is IMHO not good in terms of any security considerations, but I will not complain here.)


 I still think, however, the 0x40 command should not have made it into releases of this library (in contrast to a preview branch), if this library or the tools claim to be a compliant fido 2.0 client.

Reading the spec (2.0) the reasoning seems simple (please correct me if I am wrong)

> Command codes in the range between authenticatorVendorFirst [i.e. 0x40] and authenticatorVendorLast [i.e. 0xBF] may be used for vendor-specific implementations.

That is why anybody has the right to use these for what they like in their **non-standard** tools.

> Note that the FIDO client will never generate these commands.

That means that libfido is not a FIDO 2.0 compliant client anymore!

I actually don't believe you that 0x40 and 0x41 will be part of FIDO 2.1 (without having read the spec). They are just used to test the preview.

 Looking at the chrome code 
` kAuthenticatorCredentialManagement = 0x0a` seems to be the final command code (without knowing the final spec). This makes actually much more sense, because it is reserved and outside the vendor range.

0x40 shouldn't be IMHO be used in release, i.e. non-preview, software. 

Or they at least need to be guarded like chrome does:

https://github.com/chromium/chromium/blob/758e09418a0b84495eddd13622bd052020be0f30/device/fido/credential_management.cc#L376-L378

Other vendors are not at fault using 0x40 for anything they like! This seems to be the purpose of the spec.

I am just worried that testing code makes it into a lot of software and it might be difficult to remove or check.

Having said that I think is really stupid practice to use at least the first vendor commands in any preview testing because IMHO it is likely that other vendors will use the first one for their own stuff.

**Comment by martelletto** [comment]
Hi,

> I still think, however, the 0x40 command should not have made it into releases of this library (in contrast to e.g. a preview branch), if this library or the tools claim to be a compliant fido 2.0 client.
> 
> Reading the spec (2.0) the reasoning seems simple (please correct me if I am wrong)
> 
> > Command codes in the range between authenticatorVendorFirst [i.e. 0x40] and authenticatorVendorLast [i.e. 0xBF] may be used for vendor-specific implementations.
> 
> That is why anybody has the right to use these for what they like in their **non-standard** tools.
> 
> > Note that the FIDO client will **never** generate these commands.
> 
> That means that libfido or the its tools are not a FIDO 2.0 compliant client anymore!

Right, because FIDO_2_1_PRE is not strictly compatible with FIDO_2_0 due to the choice of command bytes. Note, however, that it is possible for an application to distinguish between them by looking at the version, extension, and option strings returned by fido_dev_get_cbor_info().

Likewise, a vendor extending 0x40 for their own purpose could reasonably be expected to indicate the allocation of the command byte through an extension or option string. This is perhaps the rationale behind FIDO's decision to borrow from the vendor-specific range. I don't know, and there is no point engaging in conjecture.

> I guess that 0x40 and 0x41 will be part of FIDO 2.1 (without having read the spec). They are just used to test the preview.
> 
> Looking at the chrome code
> ` kAuthenticatorCredentialManagement = 0x0a` seems to be the final command code (without knowing the final spec). This makes actually much more sense, because it is reserved and outside the vendor range.
> 
> 0x40 shouldn't be IMHO be used in release, i.e. non-preview, software.

Then don't use it? :) There is nothing forcing an application to call fido_credman(). The reality, however, is that there are devices on the field, from multiple vendors, with support for 0x40. Not providing access to a feature because of a clash of command bytes, or because the spec hasn't been finalised, is not a decision a library should make. A library should offer possibilities: at the moment, it is possible for an application to detect FIDO_2_1_PRE and make use of 0x40 through fido_credman() if it wants to.

> Or they at least need to be guarded like chrome does:
> 
> https://github.com/chromium/chromium/blob/758e09418a0b84495eddd13622bd052020be0f30/device/fido/credential_management.cc#L376-L378

Preventing the invocation of fido_credman() if the device does not support FIDO_2_1_PRE can be done by an application with libfido2 as-is. Once FIDO 2.1 is finalised, we will probably need similar logic in libfido2 to decide which command byte to use. I would rather wait for the 2.1 spec to be public before jumping to conclusions as to what the command byte will be, though.

> Other vendors are not at fault using 0x40 for anything they like! This seems to be the purpose of the spec.
> 
> I am just worried that testing code makes it into a lot of software and it might be difficult to remove or check.

I agree, but I am afraid it might already be too late. Given the body of software with support for 0x40, my guess is that most authenticators will have to support 0x40 and 0x0a, or whatever the byte is in FIDO 2.1, meaning 0x40 is forever burnt as a vendor-specific command byte.
 
> Having said that I think is really stupid practice to use at least the first vendor commands in any preview standard because IMHO it is likely that other vendors will use the first one for their own stuff. I guess it is not totally fatal because likely the commands will just fail, but I could imagine some really stupid side effects.

I understand. It is indeed unfortunate. Keep in mind that detection of preview or vendor capability is possible through fido_dev_get_cbor_info(), though.

-p.

**Comment by riedel** [comment]
OK. Although I am not fully convinced that it is good if users need to check capabilities that officially do not exist yet. My feeling is that at least the tools should do the check as you describe. 

But at least this issue should describe everything needed, if somebody ends up as puzzled as me trying to find out why their key is not doing what is expected (library says its FIDO2, key says its FIDO2, you end up with errors and have to read the spec...)

Maybe it is also simply a documentation issue of the library functions (ie. don't call this unless you have at least a certain protocol version). But I think you have your reasons, i.e. defacto standardization. 

Thanks for all the explaination behind your reasoning and your openess! (Other API vendors, ie. Microsoft, are much less open about their rather drastic design decisions, see #34 :) ).

I guess it makes sense to wait for 2.1PRE then to implement deleting and hope that I don't run out of resident keys in the meantime :)
