### ISSUE TITLE
70-u2f.rules: libfido2 vs libu2f-host

### ISSUE THREAD

**Issue by tgurr** [Yubico/libfido2#131]
* Both libfido2 and libu2f-host come with the same 70-u2f.rules file, which raises the question how do we solve this on a packaging level?
* And worse, there are even differences between the two 70-u2f.rules from libfido2 and libu2f-host (diff from both current git master files).

```
--- libfido2_70-u2f.rules	2020-02-24 16:48:35.575208105 +0100
+++ libu2f-host_70-u2f.rules	2020-02-24 16:48:44.381128909 +0100
@@ -1,6 +1,17 @@
-# Copyright (c) 2018 Yubico AB. All rights reserved.
-# Use of this source code is governed by a BSD-style
-# license that can be found in the LICENSE file.
+# Copyright (C) 2013-2015 Yubico AB
+#
+# This program is free software; you can redistribute it and/or modify it
+# under the terms of the GNU Lesser General Public License as published by
+# the Free Software Foundation; either version 2.1, or (at your option)
+# any later version.
+#
+# This program is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
+# General Public License for more details.
+#
+# You should have received a copy of the GNU Lesser General Public License
+# along with this program; if not, see <http://www.gnu.org/licenses/>.
 
 # this udev file should be used with udev 188 and newer
 ACTION!="add|change", GOTO="u2f_end"
@@ -35,11 +46,8 @@
 # Thetis Key
 KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1ea8", ATTRS{idProduct}=="f025", TAG+="uaccess", GROUP="plugdev", MODE="0660"
 
-# Nitrokey FIDO U2F, Nitrokey FIDO2
-KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="4287|42b1", TAG+="uaccess", GROUP="plugdev", MODE="0660"
-
-# Safetech SafeKey
-KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="42b3", TAG+="uaccess", GROUP="plugdev", MODE="0660"
+# Nitrokey FIDO U2F, Nitrokey FIDO2, Safetech SafeKey
+KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="4287|42b1|42b3", TAG+="uaccess", GROUP="plugdev", MODE="0660"
 
 # Google Titan U2F
 KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="18d1", ATTRS{idProduct}=="5026", TAG+="uaccess", GROUP="plugdev", MODE="0660"
@@ -72,4 +80,7 @@
 # OnlyKey (FIDO2 / U2F)
 KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="60fc", TAG+="uaccess", GROUP="plugdev", MODE="0660"
 
+# GoTrust Idem Key
+KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1fc9", ATTRS{idProduct}=="f143", TAG+="uaccess", GROUP="plugdev", MODE="0660"
+
 LABEL="u2f_end"
```

Additionally we have:

* `60-fido-id.rules` installed by systemd/udev itself https://github.com/systemd/systemd/commit/d45ee2f31a8358db0accde2e7c81777cedadc3c2.

* `60-u2f-hidraw.rules` installed by u2f-hidraw-policy. https://github.com/amluto/u2f-hidraw-policy/blob/master/60-u2f-hidraw.rules

* `69-yubikey.rules` and `70-yubikey.rules` installed by yubikey-personalization. https://github.com/Yubico/yubikey-personalization/blob/master/69-yubikey.rules https://github.com/Yubico/yubikey-personalization/blob/master/70-yubikey.rules

This makes it really messy, for example previously we had to add a runtime dependency to yubikey-manager on libu2f-host, solely because libu2f-host ships udev rules required for some devices. It would be great if the required udev rules could just be upstreamed to udev/systemd, but I'm not sure how feasible that is.

**Comment by martelletto** [comment]
Hi,

It is indeed a mess. Going forward, I believe https://github.com/systemd/systemd/commit/d45ee2f31a8358db0accde2e7c81777cedadc3c2 to be a sensible approach.

If udev rules are needed, the official position from Yubico (@kongeo, please correct me if I am wrong) is that libfido2's udev rules should be used. Since there are LTS releases that still package libfu2f-host, we (Yubico and external collaborators like me) try to keep libfido2's and libu2f-host's rules in sync.

As you found out, that is not always the case. When this happens, we kindly ask you to provide a PR to correct the problem. Other than the license, there shouldn't be differences between libu2f-host's udev rules and libfido2's.

-p.

**Comment by roycewilliams** [comment]
If feasible, I'd like to ensure that non-systemd-dependent configuration paths are also preserved.

I'd also like to propose that to minimize drift and improve ease of maintenance, a formal **sorting method** be identified. PRs place new entries wherever they happen to choose. A formal sorting method could be placed in the comments at the top of the file, making it easy for causal PRs to conform. Personally, I'd recommend **sorting by Vendor ID in hex order** as the least ambiguous and easiest to follow option. (In a couple of cases, this may mean that one organizations' entries will be in more than one location, because they have used more than one Vendor ID over time, but I think that's a reasonable price to pay in exchange for the 100% clarity of sorting by a hex value, instead of the fuzzier organization company names, model names, etc.). I would further suggest that within each Vendor ID, the **Product IDs should also be sorted** in hex order.

If this sorting method is agreeable, I'll submit PRs that applies it, and also pushes the superset of all devices to each file.

**Comment by martelletto** [comment]
Hi @roycewilliams,

Apologies for the delay.

I have pushed (on a branch) a tentative restructuring of the representation used to keep track of known FIDO authenticators:

- [udev/fidodevs](https://github.com/Yubico/libfido2/blob/fidodevs/udev/fidodevs) contains a sorted list of vendors and products;
- [udev/check.sh](https://github.com/Yubico/libfido2/blob/fidodevs/udev/check.sh) can be run (e.g., from CI) to ensure fidodevs is correctly sorted;
- [udev/devlist2udev.awk](https://github.com/Yubico/libfido2/blob/fidodevs/udev/devlist2udev.awk) produces a [udev ruleset](https://github.com/Yubico/libfido2/blob/fidodevs/udev/70-u2f.rules) from fidodevs.

What do you think? CC'ing @klali @a-dma, who may be interested in this.

This approach was heavily inspired by how OpenBSD and NetBSD [keep track of known USB devices](https://github.com/openbsd/src/blob/master/sys/dev/usb/usbdevs).

**Comment by roycewilliams** [comment]
Wow, @martelletto - impressive! Simple, clear, and maintainable.

And no worries at all about the delay - there's ... a lot going on.
