### ISSUE TITLE
Build on freebsd.

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#219]
Hi,
I get below error during cmake on freebsd.

CMake Error at src/CMakeLists.txt:50 (message):
  please define a hid backend for your platform

Is it compulsory to use -DUSE_HIDAPI to build on freebsd ?

**Comment by nevun** [comment]
Hi

tl;dr: yes

You could get some hints from FreeBSDs own ports system where they build `libfido2`: https://svnweb.freebsd.org/ports/head/security/libfido2/?pathrev=547802

Also if you are on a FreeBSD version older than 11, I suspect you can just do `pkg install libfido2`.

See https://www.freshports.org/security/libfido2/

**Comment by sb230132** [comment]
Hi,
Will the changes mentioned in below link be ported back ?
https://svnweb.freebsd.org/ports/head/security/libfido2/?pathrev=547802

**Comment by nevun** [comment]
They have three patches there: `https://svnweb.freebsd.org/ports/head/security/libfido2/files/?pathrev=547802`

* the cmake one is weird because FreeBSD does or cannot use OpenBSD's `hid_openbsd.c` so that one is not necessary

* the cbor.c patch is taken from a libfido2 commit 15 days ago as it says in its comment, this means that patch will be included in the next release of libfido2

* the last patch, for `hid_openbsd.c` is only needed because of the incorrect cmake patch

FreeBSD uses the hidapi as you can see in their `Makefile` on line 21: https://svnweb.freebsd.org/ports/head/security/libfido2/Makefile?view=markup&pathrev=547802#l21
