### ISSUE TITLE
can't open device on OpenBSD

### ISSUE THREAD

**Issue by edgarpettijohn** [Yubico/libfido2#3]
It's possible I'm just not using the library correctly. However, I could open the device with open(2). When I do it shows the following in dmesg:
uhid0 at uhidev0: input=64, output=64, feature=0
Not sure if that helps or not.

laptop$ cat fido.c

```

int
main(void)
{
        fido_dev_t *d;
        int fd;

        d = fido_dev_new();
        if (d == NULL)
               err(1, "fido_dev_new");

        fido_init(FIDO_DEBUG);

        fd = fido_dev_open(d, "/dev/uhid0");
        
        printf("%d\n", fd);

        return 0;
}

```

laptop$ ./fido
fido_dev_open_tx: dev->io.open
-9

**Comment by martelletto** [comment]
fido_dev_open() returns a status code, and not a descriptor; see 
https://developers.yubico.com/libfido2/Manuals/fido_dev_open.html. 
You are otherwise using the library correctly. Depending on how  
libhidapi was built, you will need to pass fido_dev_open() a 
libusb-specific identifier string such as '0001:0002:00' instead of 
the uhid(4) path. if that doesn't work, i would appreciate if you 
could ktrace fido.c, so we could have a better understanding of 
what's going on.

-p.

**Comment by edgarpettijohn** [comment]
How do I get the libusb-specific identifier? I've been playing with libusb, but no luck so far. Its easy enough to create a dumbed down version of lsusb, but I'm not sure what the '0001:0002:00' fields would correspond to.

**Comment by edgarpettijohn** [comment]
I did have to make the change to hid.c to get fido2-token to work.

```
#include <err.h>
#include <fido.h>
#include <stdio.h>

int
main(void)
{
        fido_dev_t *d;
        int error;

        d = fido_dev_new();
        if (d == NULL)
                errx(1, "fido_dev_new");

        fido_init(FIDO_DEBUG);

        /* path from fido2-token -L */
        error = fido_dev_open(d, "0000:0004:00");
        if (error != FIDO_OK)
                errx(1, "fido_dev_open");

        fido_dev_close(d);
        fido_dev_free(&d);

        return 0;
}

```
I now get the following:
laptop$ ./fido
tx: d=0xdc26fa1100, cmd=0x86, buf=0xdc26fa1100, count=8
  18 f9 fa 1b 22 7e 19 d2 
tx: tx_preamble
fido_dev_open_tx: tx

It just sits there without returning until I kill it.

**Comment by martelletto** [comment]
ok, that is what i am seeing as well. as a next step, could you try 
to use usbhidctl -f /dev/uhidX -r to dump the device's report 
descriptor? if that works, you could try to establish contact with 
the device using something like this:

#include <err.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int
main(void)
{
        int fd;
        unsigned char out[64];
        unsigned char in[64];
        ssize_t n;

        if ((fd = open("/dev/uhidX", O_RDWR)) < 0)
                err(1, "open");

        memset(&out, 0, sizeof(out));
        if ((n = write(fd, out, sizeof(out))) < 0)
                err(1, "write");
        if ((size_t)n != sizeof(out))
                err(1, "short write");

        n = read(fd, in, sizeof(in));
        printf("n=%zd\n", n);
}

**Comment by edgarpettijohn** [comment]
write(2)ing to the device seems to work. However, read(2)ing just sits there until I kill it.

**Comment by martelletto** [comment]
ok, that is what i am seeing as well. thanks for testing. the two
problems (libhidapi not filling the device's usage info and our
inability to read from the device) could be related. i will give
openbsd's libhidapi port a closer look to see what it is doing.

-p.

**Comment by edgarpettijohn** [comment]
just noticed this test from libhidapi
laptop$ ./hidtest
Device Found
  type: 1ea8 f025
  path: 0000:0004:00
  serial_number: (null)
  Manufacturer: ExcelSecu
  Product:      EsecuFIDO HID
  Release:      100
  Interface:    0

Manufacturer String: ExcelSecu
Product String: EsecuFIDO HID
Unable to read serial number string
Serial Number String: (0) 
Indexed String 1: ExcelSecu
Feature Report
   01 03 04 6f fb 00 00 00 
Unable to write()
Error: (null)
Unable to write() (2)
waiting...
waiting...
waiting...
waiting...

**Comment by martelletto** [comment]
i got it to a working state, but the solution isn't pretty, and 
there are still problems. first of all, in order to use openbsd's 
libhidapi port, we need to make sure that the key doesn't attach as 
a uhid(4) or uhidev(4) device. this can be done through config(8), 
and is mentioned in the README of the libhidapi package:

https://github.com/openbsd/ports/blob/master/comms/libhidapi/pkg/README

normally, the otp interface of a yubikey will attach as a keyboard 
(ukbd(4) over uhidev(4)), the u2f interface as a uhid(4) over 
uhidev(4), and the ccid interface as a ugen(4). by disabling 
uhid(4) and uhidev(4) in the kernel, the intended effect is to have 
a yubikey's u2f interface attach as a ugen(4) instead. however, that 
is not what happens: disabling uhid(4) and uhidev(4) causes the otp 
and u2f interfaces to be ignored, with the ccid interface attaching 
as a ugen(4).

to get the u2f interface to attach as a ugen(4), i had to use 
yubico's personalization tool to disable otp and ccid.

the next step was to rebuild the libhidapi package with 
INVASIVE_GET_USAGE, as in the diff below. despite its name, there 
doesn't seem to be anything invasive about INVASIVE_GET_USAGE; the 
concern about having to reattach the kernel driver is most likely 
linux-specific.

Index: patches/patch-libusb_hid_c
===================================================================
RCS file: /cvs/ports/comms/libhidapi/patches/patch-libusb_hid_c,v
retrieving revision 1.1.1.1
diff -u -p -u -p -r1.1.1.1 patch-libusb_hid_c
--- patches/patch-libusb_hid_c	18 Jun 2018 23:37:01 -0000	1.1.1.1
+++ patches/patch-libusb_hid_c	5 Jul 2018 10:39:51 -0000
@@ -5,6 +5,15 @@ rename hid_init() to hidapi_hid_init() t
 Index: libusb/hid.c
 --- libusb/hid.c.orig
 +++ libusb/hid.c
+@@ -132,7 +132,7 @@ this is very invasive as it requires the detach
+ and re-attach of the kernel driver. See comments inside hid_enumerate().
+ libusb HIDAPI programs are encouraged to use the interface number
+ instead to differentiate between interfaces on a composite HID device. */
+-/*#define INVASIVE_GET_USAGE*/
++#define INVASIVE_GET_USAGE
+ 
+ /* Linked List of input reports received from the device. */
+ struct input_report {
 @@ -490,7 +490,7 @@ static char *make_path(libusb_device *dev, int interfa
  }
  
finally, i had to modify fido_dev_open_rx() to try to read from the 
device a second time, as in the diff below. for some reason, the 
first read returns an empty frame.

diff --git a/src/dev.c b/src/dev.c
index 92f4cc8..73b8afd 100644
--- a/src/dev.c
+++ b/src/dev.c
@@ -104,7 +104,13 @@ fido_dev_open_rx(fido_dev_t *dev, int ms)
 	const uint8_t	cmd = CTAP_FRAME_INIT | CTAP_CMD_INIT;
 	int		r;
 
-	if ((r = rx(dev, cmd, &dev->attr, sizeof(dev->attr), ms)) < 0) {
+	r = rx(dev, cmd, &dev->attr, sizeof(dev->attr), ms);
+	if (r < 0) {
+		/* this sometimes happens under openbsd. try again */
+		log_debug("%s: retrying", __func__);
+		r = rx(dev, cmd, &dev->attr, sizeof(dev->attr), ms);
+	}
+	if (r < 0) {
 		log_debug("%s: rx", __func__);
 		return (FIDO_ERR_RX);
 	}

with these modifications in place, fido2-token -L works, and 
fido2-token -I <device> prints information about <device>, but hangs 
due to hid_close() blocking indefinitely. i haven't investigated why 
that is happening.

-p.

**Comment by martelletto** [comment]
thanks for testing. it would be interesting to look into a libhidapi 
backend for openbsd that used uhid(4) instead of libusb. disabling 
uhid(4) and uhidev(4) in the kernel to get libhidapi working is not 
a reasonable long-term solution (we are asking the user to choose 
between libhidapi and a working usb keyboard/mouse). there isn't 
much that can be done in libfido2 to resolve the issue. i am sorry 
:(.

-p.
