### ISSUE TITLE
After upgrading libfido2 from 1.6.0 to 1.7.0, systemd-cryptenroll stopped working with canokeys

### ISSUE THREAD

**Issue by hexchain** [Yubico/libfido2#322]
**What version of libfido2 are you using?**
1.6.0, 1.7.0

**What operating system are you running?**
Arch Linux

**What application are you using in conjunction with libfido2?**
`systemd-cryptenroll`

**How does the problem manifest itself?**
`systemd-cryptenroll` is able to enroll an encrypted volume with libfido2 1.6.0, but fails to do so with 1.7.0 on the same system with the same key. The source code of the enrolling process (which seems to be `fido2-cred` + `fido2-assert` with hmac-secret) can be found here: 

https://github.com/systemd/systemd/blob/v248/src/shared/libfido2-util.c#L433:5
called by: https://github.com/systemd/systemd/blob/v248/src/cryptenroll/cryptenroll-fido2.c#L34

**Is the problem reproducible?**
Yes.

**What are the steps that lead to the problem?**
On 1.7.0, executing the enrolling command fails with the following error:
```
% sudo systemd-cryptenroll --fido2-device=auto /dev/some_luks_partition
...
Generating secret key on FIDO2 security token.
Failed to ask token for assertion: FIDO_ERR_MISSING_PARAMETER
```

**Does the problem happen with different authenticators?**
I don't have other keys, unfortunately. The source code of Canokeys can be found here: https://github.com/canokeys/canokey-core

cc @ZenithalHourlyRate from Canokeys

**Please include the output of `fido2-token -L`.**

<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
% fido2-token -L
/dev/hidraw0: vendor=0x20a0, product=0x42d4 (canokeys.org CanoKey)
</pre>
</details>

**Please include the output of `fido2-token -I`.**

<details>
<summary><code>fido2-token -I</code></summary>
<br>
<pre>
% fido2-token -I /dev/hidraw0
proto: 0x02
major: 0x01
minor: 0x00
build: 0x00
caps: 0x04 (nowink, cbor, msg)
version strings: FIDO_2_0, U2F_V2
extension strings: hmac-secret
aaguid: 244eb29ee0904e4981fe1f20f8d3b8f4
options: rk, noclientPin
maxmsgsiz: 1280
maxcredcntlst: 0
maxcredlen: 0
fwversion: 0x0
pin protocols: 1
pin retries: undefined
uv retries: undefined
</pre>
</details>

**Please include the output of `FIDO_DEBUG=1`.**

`systemd-cryptenroll` does not call `fido_init`, so the following output is based on a modified build, in which I added a call to `fido_init` after `dlopen`.

<details>
<summary><code>FIDO_DEBUG=1</code></summary>

```
% # create a LUKS disk image
% truncate -s 1G disk.img
% sudo losetup -f --show disk.img
% sudo cryptsetup format /dev/loop0

WARNING!
========
This will overwrite data on /dev/loop0 irrevocably.

Are you sure? (Type 'yes' in capital letters): YES
Enter passphrase for /home/hexchain/tmp/disk.img:
Verify passphrase:
```
```
% sudo FIDO_DEBUG=1 ./systemd-cryptenroll --fido2-device=auto /dev/loop0
```

With libfido2 1.7.0: http://ix.io/2VCm
With libfido2 1.6.0: http://ix.io/2VCn

</details>

**Comment by martelletto** [comment]
Thank you for the detailed report.

The problem seems to be here: https://github.com/canokeys/canokey-core/blob/master/applets/ctap/ctap-parser.c#L407. FIDO 2.0, which CanonKey's firmware implements, does not specify a fourth key in a hmac-secret's authenticatorGetAssertion map (submap), which FIDO 2.1 does; compare _authenticatorGetAssertion additional behaviors_ in https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#sctn-hmac-secret-extension with the same section in https://fidoalliance.org/specs/fido-v2.1-rd-20210309/fido-client-to-authenticator-protocol-v2.1-rd-20210309.html#sctn-hmac-secret-extension, where a fourth `pinUvAuthProtocol` (optional) key is present.

FIDO 2.0, however, specifies that:

> If map keys are present that an implementation does not understand, they MUST be ignored. Note that this enables additional fields to be used as new features are added without breaking existing implementations.

(in https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#message-encoding), which seems incompatible with the line of code referenced above.

-p.

**Comment by hexchain** [comment]
Thank you for your quick and detailed response!
