### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#43]
I'm (trying to) implement a Rust wrapper for this library. I was wondering: how thread safe is this library?

**Comment by martelletto** [comment]
libfido2 is mostly threading-friendly, with minimal shared global state.

With the code as it stands, the only function you have to be careful
with is fido_init, which tells the library whether to emit debug output.
Since fido_init is a one-shot initialisation function, you are unlikely
to experience problems as long as you call it from the corresponding
path of your wrapper.

For everything else, usual precautions apply: grab a read lock when
passing API objects to functions that take a const pointer (e.g. a const
fido_cred_t * and fido_cred_pubkey_ptr) and a write lock otherwise (e.g.
a fido_cred_t * and fido_dev_make_cred).

I will fix the fido_init nit in the next version of libfido2. Thanks for
bringing it to my attention.

Hope that helps!

-p.

**Comment by PvdBerg1998** [comment]
@martelletto Just to be sure, this means I can create (allocate) any structure on thread A, access it read only from thread B, and then pass it to thread C? (In Rust terms: I can implement the Send and Sync traits)?

**Comment by PvdBerg1998** [comment]
The fido_init I solved atomically, it gets run exactly once, from the first thread to execute any functionality.

**Comment by martelletto** [comment]
On 23/06/2019 12:35, Pim van den Berg wrote:
> @martelletto Just to be sure, this means I can create (allocate) any structure on thread A, access it read only from thread B, and then pass it to thread C? (In Rust terms: I can implement the Send and Sync traits)?
> 

Yes, that should work.

-p.

**Comment by PvdBerg1998** [comment]
@martelletto I have another question and I don't want to open another issue: can I rely on any strings being valid utf8 (or ascii)?

**Comment by martelletto** [comment]
Hi, no problem. Yes, you can rely on strings being valid UTF-8.
