### ISSUE TITLE
fido_winhello_get_cbor_info: return uv = true?

### ISSUE THREAD

**Issue by github-cygwin** [Yubico/libfido2#521]
Hi,

I'm working on Cygwin WinHello support for OpenSSH-portable and I'm stumbling over something I don't understand.
WinHello provides user verification, i. e., it provides a dialog to enter the FIDO2 PIN.  However, when OpenSSH
calls fido_dev_get_cbor_info to check for the "uv" option, it draws a blank, because fido_winhello_get_cbor_info
doesn't return a "uv" entry at all.

Is that correct, and if so, why?  I'm asking to make sure I'm doing the right thing in OpenSSH.

Thanks,
Corinna

**Comment by martelletto** [comment]
The actual conversation took place in a different forum, so I will note the main takeaway: as pointed out by @github-cygwin, it does make sense to have fido_winhello_get_cbor_info() list UV instead of clientPin in its list of supported options (https://github.com/Yubico/libfido2/blob/master/src/winhello.c#L886).
